/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queuploader;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Phavour
 */
public class TeacherAccount extends javax.swing.JFrame {
	
	/**
	 * Creates new form adimAccount
	 */
	public TeacherAccount() {
		initComponents();
		userNameText.setText("Teacher Can't be Changed");
		flashHandler();
		loadPword();
	}
	
	private void flashHandler(){
		oldPwordLb.setForeground(Color.WHITE);
		confirmPwordLb.setForeground(Color.WHITE);
	}
	
	private String pWord = "";
	private void loadPword(){
				
//		try {
//			String query = "SELECT p_word FROM adminLogin"
//						+ " WHERE e_mail = 'Bright'";
//			PreparedStatement pst = connect.prepareStatement(query);
//			ResultSet rs = pst.executeQuery();
//
//			while(rs.next()) {
//				pWord = rs.getString(1);
//			}
//
//			pst.close();
//			rs.close();
//		} catch (SQLException ex) {
//			ex.printStackTrace();
//		}
		
		
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        subBtn5 = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        oldPwordLb = new javax.swing.JLabel();
        oldPwordText = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newPwordText = new javax.swing.JTextField();
        confirmPwordLb = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        confirmPwordText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Password");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cancelBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_25px_1.png"))); // NOI18N
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelBtnMousePressed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Username");

        userNameText.setEditable(false);
        userNameText.setBackground(new java.awt.Color(243, 243, 243));
        userNameText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userNameText.setForeground(new java.awt.Color(51, 51, 51));
        userNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextActionPerformed(evt);
            }
        });

        subBtn5.setBorder(null);
        subBtn5.setText("UPDATE");
        subBtn5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        subBtn5.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        subBtn5.setkEndColor(new java.awt.Color(0, 204, 204));
        subBtn5.setkHoverEndColor(new java.awt.Color(0, 224, 224));
        subBtn5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        subBtn5.setkHoverStartColor(new java.awt.Color(0, 224, 224));
        subBtn5.setkSelectedColor(new java.awt.Color(0, 204, 204));
        subBtn5.setkStartColor(new java.awt.Color(0, 204, 204));
        subBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtn5ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_male_circle_96px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 224, 224));
        jLabel2.setText("Can't be modified.");

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Old Password");

        oldPwordLb.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        oldPwordLb.setForeground(new java.awt.Color(255, 0, 0));
        oldPwordLb.setText("Wrong password");

        oldPwordText.setBackground(new java.awt.Color(243, 243, 243));
        oldPwordText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        oldPwordText.setForeground(new java.awt.Color(51, 51, 51));
        oldPwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPwordTextActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("New Password");

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 224, 224));
        jLabel4.setText("Use what you can remember or back it up.");

        newPwordText.setBackground(new java.awt.Color(243, 243, 243));
        newPwordText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        newPwordText.setForeground(new java.awt.Color(51, 51, 51));
        newPwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPwordTextActionPerformed(evt);
            }
        });

        confirmPwordLb.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        confirmPwordLb.setForeground(new java.awt.Color(255, 0, 0));
        confirmPwordLb.setText("Password not matched");

        jLabel51.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Confirm Password");

        confirmPwordText.setBackground(new java.awt.Color(243, 243, 243));
        confirmPwordText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        confirmPwordText.setForeground(new java.awt.Color(51, 51, 51));
        confirmPwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPwordTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameText)
                            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oldPwordLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oldPwordText)
                            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(newPwordText)
                            .addComponent(confirmPwordLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmPwordText))
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel48)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel49)
                .addGap(1, 1, 1)
                .addComponent(oldPwordLb)
                .addGap(1, 1, 1)
                .addComponent(oldPwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel50)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(newPwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel51)
                .addGap(1, 1, 1)
                .addComponent(confirmPwordLb)
                .addGap(1, 1, 1)
                .addComponent(confirmPwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(subBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMousePressed

    }//GEN-LAST:event_cancelBtnMousePressed

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void userNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextActionPerformed

    private void subBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtn5ActionPerformed

		loadPword();
		
        if(!oldPwordText.getText().equals("")
				&&!newPwordText.getText().equals("")
				&&!confirmPwordText.getText().equals("")){
				
				flashHandler();
				
				if(oldPwordText.getText().equals(pWord)){
					
					if(newPwordText.getText().equals(confirmPwordText.getText())
							&&!newPwordText.getText().equals(oldPwordText.getText())
							&&!newPwordText.getText().equals("")
							&&!confirmPwordText.getText().equals("")){
						
//						try{
//							String query =  "UPDATE adminlogin"
//										+ " SET p_word   = '"+confirmPwordText.getText()+"'"
//										+ " WHERE e_mail = 'Bright'";
//							PreparedStatement pst = connect.prepareStatement(query);
//							pst.execute();
//							JOptionPane.showMessageDialog(null, "Successful");
//							pst.close();
//						}catch(SQLException e){
//							e.printStackTrace();
//						}
						
					}else{
						confirmPwordLb.setForeground(Color.red);
					}
					
				}else{
					oldPwordLb.setForeground(Color.red);
				}
			
        }else{

        }
    }//GEN-LAST:event_subBtn5ActionPerformed

    private void oldPwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPwordTextActionPerformed

    private void newPwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPwordTextActionPerformed

    private void confirmPwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPwordTextActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TeacherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TeacherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TeacherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TeacherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TeacherAccount().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelBtn;
    private javax.swing.JLabel confirmPwordLb;
    private javax.swing.JTextField confirmPwordText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newPwordText;
    private javax.swing.JLabel oldPwordLb;
    private javax.swing.JTextField oldPwordText;
    private keeptoo.KButton subBtn5;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
